site_name: HttpCommand
repo_url: https://github.com/dyalog/httpcommand
repo_name: Dyalog/HttpCommand
nav:
    - Home: 'index.md'
    - Learn: 'learn.md'
    - Reference:
      - Overview: 'overview.md'
      - 'Quick Reference': 'quick.md'
      - 'Detailed Reference': 'reference.md'
    - About: 
      - License: 'LICENSE.md'
      - 'Release Notes': 'release-notes.md'

theme:
  favicon: 'img/favicon-32.png'
  logo: 'img/dyalog-white.svg'
  features:
    - navigation.sections
    - navigation.instant
  name: material

extra_css:
  - css/main.css

plugins:
  - search

markdown_extensions:
  - admonition
  - abbr

  