site_name: HttpCommand
repo_url: https://github.com/dyalog/httpcommand
repo_name: Dyalog/HttpCommand
dev_addr: 127.0.0.1:22222
copyright: Copyright &copy; 2015-2022 <strong><a href="https://dyalog.com">Dyalog, LTD</a></strong>
nav:
    - Overview: 'index.md'
    - Usage:
      - 'Quick Start': 'quickstart.md' # complete
      - 'Usage Guide': 'userguide.md'   # complete
      - 'Examples': 'examples.md'      # complete
      - 'Troubleshooting': 'trouble.md' # complete
    - Reference:
      - 'Settings':
        - 'Request-related Settings': 'request-settings.md' # complete
        - 'Operational Settings': 'operational-settings.md' # complete
        - 'Conga-related Settings': 'conga-settings.md'     # complete
        - 'Proxy-related Settings': 'proxy-settings.md'     # complete
      - 'Shared Methods':
        - 'Shortcut Methods': 'shortcut-methods.md' # complete
        - 'Encode/Decode Methods': 'encode-methods.md' # complete
        - 'Miscellaneous Methods': 'misc-methods.md' # complete
      - 'Instance Methods': 'instance-methods.md' # complete
      - 'Result Namespace':
        - 'Operational Elements': 'result-operational.md' # complete
        - 'Request Elements': 'result-request.md' # complete
        - 'Response Elements': 'result-response.md' # complete
      - 'Messages and Return Codes': 'msgs.md' # complete
    - Advanced Topics:
      - 'HttpCommand and Conga' : 'conga.md' # complete
      - 'Secure Communications' : 'secure.md' # complete
      - 'Using a Proxy Server': 'proxy.md' 
      - 'Integrating HttpCommand' : 'integrating.md' # complete
    - About: 
      - License: 'LICENSE.md' # complete
      - 'Release Notes': 'release-notes.md'

theme:
  favicon: 'img/favicon-32.png'
  logo: 'img/dyalog-white.svg'
  features:
    - navigation.sections
    - navigation.instant
  name: material

extra: 
  generator: false

extra_css:
  - css/main.css

plugins:
  - search
  - print-site:
      add_to_navigation: true
      print_page_title: 'Print'
      add_print_site_banner: false
      # Table of contents
      add_table_of_contents: false
      toc_title: 'Table of Contents'
      toc_depth: 6
      # Content-related
      add_full_urls: false
      enumerate_headings: false
      enumerate_figures: false
      add_cover_page: true
      cover_page_template: ""
      path_to_pdf: ""
      include_css: true
      enabled: true
      exclude:

markdown_extensions:
  - admonition
  - abbr
  - footnotes
  - attr_list 
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      title: On this page