site_name: HttpCommand
repo_url: https://github.com/dyalog/httpcommand
repo_name: Dyalog/HttpCommand
dev_addr: 127.0.0.1:22222
copyright: Copyright &copy; 2015-2022 <strong><a href="https://dyalog.com">Dyalog, LTD</a></strong>
nav:
    - Overview: 'index.md'
    - Usage:
      - 'Quick Start': 'quickstart.md'
      - 'User Guide': 'userguide.md'
      - 'Examples': 'usecases.md'
      - 'Troubleshooting': 'trouble.md'
    - Reference:
      - 'Configuration': 'configuration.md'
      - 'Shared Methods': 'shared.md'
      - 'Instance Methods': 'instance.md'
      - 'Result Namespace': 'result.md'
      - 'Messages and Return Codes': 'msgs.md'
    - Advanced Topics:
      - 'HttpCommand and Conga' : 'conga.md'
      - 'Secure Communications' : 'secure.md'
      - 'Integrating HttpCommand' : 'integrating.md'
    - About: 
      - License: 'LICENSE.md'
      - 'Release Notes': 'release-notes.md'

theme:
  favicon: 'img/favicon-32.png'
  logo: 'img/dyalog-white.svg'
  features:
    - navigation.sections
    - navigation.instant
  name: material

extra: 
  generator: false

extra_css:
  - css/main.css

plugins:
  - search

markdown_extensions:
  - admonition
  - abbr
  - footnotes
  - toc:
      title: On this page